# Numpy

[numpy官方文档](https://numpy.org/doc/stable/reference/)

In [177]:
import numpy as np
#ndarray高效的多维数组，便捷的算术功能和灵活的广播功能

# ndarray

In [2]:
np.arange(100) #numpy版本的 range 的ndarray
#type(np.arange(100)) #numpy.ndarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
np.random.rand(2,3) #rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1

array([[0.89199571, 0.51772726, 0.64159027],
       [0.75270486, 0.32134083, 0.95337597]])

In [4]:
np.random.randn(2,3) #返回一个或一组样本，具有标准正态分布。

array([[-0.075917  , -0.34828164, -0.64694155],
       [ 0.29311645, -1.29848842,  0.26311527]])

## np.array

In [12]:
arr = np.array([1,2,3])
type(arr)  # numpy.ndarray
arr.shape # (3,)
arr.ndim # 1

1

In [18]:
arr2 = np.random.rand(3,5)
arr2.shape # (3, 5)
arr2.ndim # 2

2

In [21]:
arr3 = np.random.rand(3,5,2)
arr3.shape # (3, 5, 2)
arr3.ndim # 3

3

In [46]:
# 创建制定类型的数组
arr4 = np.array([1,2,3],dtype="float32")
arr4.dtype

dtype('float32')

![image.png](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202112231220825.png)

## np.empty

In [22]:
np.empty((2,3)) #并不安全，有时候会返回为初始化的垃圾数值
np.empty((2,3,2))

array([[[4.67679745e-310, 0.00000000e+000],
        [1.03977794e-312, 9.54898106e-313],
        [1.08221785e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.10343781e-312],
        [1.10343781e-312, 9.76118064e-313],
        [1.16709769e-312, 1.90979621e-312]]])

## np.zeros

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.ones

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## numpy.full

In [26]:
np.full((2,3),8,dtype='int64')

array([[8, 8, 8],
       [8, 8, 8]])

## 算术和广播

In [45]:
k = np.random.rand(2,3) 
print(k)
print(k.dtype) # 没有指定，numpy默认是float64
# 加减乘除和比较后不会改变原始数组大小

[[0.78077749 0.40777749 0.88199488]
 [0.29747855 0.19742082 0.71134188]]
float64


In [29]:
k+k

array([[0.25839222, 0.57298108, 0.90303748],
       [1.58951289, 0.12893994, 0.45413512]])

In [30]:
k*10

array([[1.29196108, 2.86490542, 4.51518739],
       [7.94756446, 0.64469971, 2.27067559]])

In [31]:
k+1

array([[1.12919611, 1.28649054, 1.45151874],
       [1.79475645, 1.06446997, 1.22706756]])

In [32]:
k/2

array([[0.06459805, 0.14324527, 0.22575937],
       [0.39737822, 0.03223499, 0.11353378]])

In [33]:
k**0.5

array([[0.3594386 , 0.53524811, 0.67195144],
       [0.89149114, 0.25390937, 0.47651606]])

In [34]:
k>1

array([[False, False, False],
       [False, False, False]])

In [35]:
k==1

array([[False, False, False],
       [False, False, False]])

In [36]:
k!=1

array([[ True,  True,  True],
       [ True,  True,  True]])

# 格式转换

In [50]:
t = np.array([0,0,0],dtype='uint8')
t[0]=1000
t

array([232,   0,   0], dtype=uint8)

In [51]:
a = [1,2,9999,127] 
np.asarray(a,dtype='int8') #-128 --127

array([  1,   2,  15, 127], dtype=int8)

In [52]:
a = [1,2,9999,244]
np.asarray(a,dtype='uint8') # 0-255

array([  1,   2,  15, 244], dtype=uint8)

In [53]:
arr = np.array([2,3,4])
# arr.astype('float64')
arr.astype('string_') #array([b'2', b'3', b'4'], dtype='|S21')
# arr.astype('unicode_')#array(['2', '3', '4'], dtype='<U21')

array([b'2', b'3', b'4'], dtype='|S21')

# 索引和切片

## 一维切片

In [54]:
#1维的和python的切片是一致的
arr_1d = np.arange(10)
arr_1d[0]
arr_1d[3:6]

array([3, 4, 5])

In [56]:
lst = [1,2,3,4]
lst[2]=8
lst #[1, 2, 8, 4]
# lst[2:]=8 #can only assign an iterable

[1, 2, 8, 4]

In [58]:
lst_np = np.array([1,2,3,4])
lst_np[2:]=8
lst_np

array([1, 2, 8, 8])

In [ ]:
赋值可以是标量或者ndarrary 不能是list

In [59]:
arr_1d = np.arange(10)
# arr_1d[2:]=[0, 1, 7, 8, 8, 8, 7, 8, 8, 8]#这样赋值不行，需要都是ndarrayz 
# ValueError: cannot copy sequence with size 10 to array axis with dimension 8

arr_1d[2:] = np.zeros(8)
arr_1d #array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
arr_1d = np.arange(10)
arr_copy = arr_1d[2:] # 这个copy是视图
arr_copy[3]= 8 #3+2 第五位 注意引用关系
arr_1d

array([0, 1, 2, 3, 4, 8, 6, 7, 8, 9])

In [62]:
arr_copy2 = arr_1d[2:].copy()

## 二维切片

In [69]:
arr_2d =np.array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ])

# 可以想象成一维的时候是一列数据 分别是1,2,3
# 二维的时候相当于增加新的列

In [78]:
arr_2d[0]  # 第一组

array([1, 2, 3])

In [79]:
arr_2d[0][2]  #第一组的 第3个
# 上述也可以简写成
arr_2d[0,2]

3

## 三维切片

In [82]:
arr_3d = np.random.randn(3,4,2)   # 最左边的可以看成最外层

In [84]:
arr_3d

array([[[-0.68264168,  0.44903741],
        [-1.1066095 , -1.0229442 ],
        [-1.35892017, -0.0663339 ],
        [-1.19793423,  0.24222114]],

       [[-0.59449874, -0.21814768],
        [-0.5921755 ,  0.89843798],
        [ 1.05658467,  1.51386083],
        [ 0.01200202,  0.33398804]],

       [[-0.16313627, -0.58689672],
        [ 0.39975886, -0.10671475],
        [ 0.00206018, -0.85378297],
        [ 0.64840862, -0.45584758]]])

In [ ]:
# 切片的时候可以当作是像洋葱一样 从里到外一层一层

In [81]:
print(arr_3d[0])
print(arr_3d[0].shape)

[[ 0.7263256   1.01585411]
 [ 0.00514739 -0.84297755]
 [-0.9224199  -1.81407031]
 [ 1.30531348 -0.86799847]]
(4, 2)


In [85]:
arr_3d[0,1:] 

array([[-1.1066095 , -1.0229442 ],
       [-1.35892017, -0.0663339 ],
       [-1.19793423,  0.24222114]])

In [80]:
# 切片的时候可以当作是像洋葱一样 从里到外一层一层

In [86]:
arr_3d[:,:1]=8 # 多维数组也可以直接赋值
arr_3d

array([[[ 8.00000000e+00,  8.00000000e+00],
        [-1.10660950e+00, -1.02294420e+00],
        [-1.35892017e+00, -6.63338996e-02],
        [-1.19793423e+00,  2.42221135e-01]],

       [[ 8.00000000e+00,  8.00000000e+00],
        [-5.92175504e-01,  8.98437981e-01],
        [ 1.05658467e+00,  1.51386083e+00],
        [ 1.20020239e-02,  3.33988041e-01]],

       [[ 8.00000000e+00,  8.00000000e+00],
        [ 3.99758855e-01, -1.06714747e-01],
        [ 2.06018264e-03, -8.53782973e-01],
        [ 6.48408621e-01, -4.55847579e-01]]])

## 布尔索引

In [87]:
arr_2d = np.random.randn(3,4)
bool_x = np.array([True,False,True])
bool_names = np.array(['jack','henry','jason'])
arr_2d[bool_x] #用bool选取0,2
arr_2d[bool_names=='jack'] #选取第一行 array([[ 1.3291973 ,  0.52318965, -0.49999786, -0.95954392]])

array([[ 0.16312037, -1.29837869, -0.0308545 ,  0.99462949]])

In [88]:
arr_2d[bool_names=='jack',2:]

array([[-0.0308545 ,  0.99462949]])

In [89]:
arr_2d[~(bool_names=='jack'),2:] #条件如果不是一个字段，要用括号括起来

array([[ 0.41495918,  0.03299783],
       [-1.40995409, -0.14450955]])

In [90]:
arr_2d[(bool_names=='jack') | (bool_names=='henry'),2:]

array([[-0.0308545 ,  0.99462949],
       [ 0.41495918,  0.03299783]])

In [91]:
arr_2d[(bool_names=='jack') & (bool_names=='henry'),2:]

array([], shape=(0, 2), dtype=float64)

In [92]:
##布尔索引总是生成一个新的对象

In [93]:
arr_2d = np.random.randn(3,4)
arr_2d

array([[-0.12258443,  0.3713189 , -0.70045145, -0.59038865],
       [ 0.24106604, -0.08346432, -0.34475861,  0.5334416 ],
       [-1.05744661,  0.47979961,  0.62199232,  2.84162327]])

In [94]:
arr_2d>0

# arr_2d[arr_2d>0]=0
# arr_2d

array([[False,  True, False, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [95]:
arr_2d!=1 #值的判断可以用!= 但是cond之间用~

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## 神奇索引

In [96]:
arr= np.empty((8,4))
for i in range(8):
    arr[i] =i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [98]:
arr[[2,1,7]] # 注意是两个括号 上面使用布尔值 这边使用index

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

## reshape和转轴

In [106]:
arr = np.arange(32).reshape(8,4) # 返回新的
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr.T # 返回新的

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [120]:
arr2 = np.arange(32).reshape(-1,4)  #缺省 4*8
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [121]:
arr2 = np.arange(32).reshape(-1,2,8)  #最外层让系统来计算
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

## 通用函数

### 一元函数

In [131]:
arr = np.arange(10).reshape(-1,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [132]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [133]:
np.ceil(arr)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [140]:
np.floor(arr)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [134]:
np.square(arr)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [135]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [137]:
np.isnan(arr)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [141]:
np.rint(arr) # 保留整数部分 保持dtype

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

### 二元函数

In [142]:
np.add(arr,arr)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### 数学统计

In [159]:
arr= np.random.randn(5,4)
arr

array([[-1.01078963, -0.5220288 ,  0.84057783, -1.56453809],
       [-1.15457758, -0.04202476, -0.28870735, -0.12363833],
       [ 1.09590559,  1.29519153, -0.30809618,  0.58349821],
       [ 0.05678   , -0.16680382, -0.31469442, -1.35455557],
       [ 0.02006958,  0.86191853,  0.74328583, -0.87269185]])

In [149]:
arr.mean() #同np.mean(arr)

0.09362223765049651

In [150]:
arr.sum()

1.8724447530099304

In [160]:
arr.mean(axis=0) # 沿0轴计算，也就是就算每列

array([-0.19852241,  0.28525054,  0.13447314, -0.66638513])

In [162]:
arr.mean(axis=1) # 沿1轴计算,也就是计算每行。 在pandas中计算每行汇总值是也是一样axis=1

array([-0.56419467, -0.402237  ,  0.66662479, -0.44481845,  0.18814552])

In [153]:
#std标准差 var方差 

![图片](https://pic4.zhimg.com/v2-dbc834c0ce121ecd73c2ae0d9fae754f_r.jpg)

### np.where

In [143]:
#np.where(cond,xarr,yarr) # 满足条件xarr,否则yarr

In [146]:
arr =np.random.randn(4,4)
np.where(arr>0,arr,0)

array([[0.59665122, 0.        , 0.        , 0.01753363],
       [0.        , 0.        , 1.3663827 , 1.83700301],
       [0.        , 0.37993148, 0.93758963, 1.43544351],
       [0.        , 0.        , 0.04743717, 0.        ]])

In [145]:
np.where(arr>0,2,-2)

array([[-2, -2, -2,  2],
       [ 2,  2,  2, -2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2]])

In [163]:
###注意和pandas中 df.where不一样 #返回一个同样shape的df，当满足条件为TRUE时，从本身返回结果，否则从返回其他df的结果

## 常用方法

### tolist

In [176]:
arr = np.random.randn(2,3)
arr = arr.astype("float16")
arr.tolist()

[[-2.025390625, -0.65185546875, -1.0107421875],
 [-0.267578125, 0.5576171875, -0.92236328125]]

### column_stack

In [185]:
a = np.array((1,2,3))
b = np.array((8,9,10))
np.column_stack( (a,b) )

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10]])

In [195]:
# 增加一列,比如增加列index列

In [198]:
c1 = np.arange(32).reshape(4,8)
c1
c2 = np.column_stack( ( c1,np.arange(4) ) )
# c2 = np.column_stack( [ c1,np.arange(4) ] ) 和上面是等价的
c2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  1],
       [16, 17, 18, 19, 20, 21, 22, 23,  2],
       [24, 25, 26, 27, 28, 29, 30, 31,  3]])

### row_stack

In [199]:
a = np.array((1,2,3))
b = np.array((8,9,10))
np.row_stack( (a,b) )

array([[ 1,  2,  3],
       [ 8,  9, 10]])

### argwhere

In [201]:
arr = np.array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
np.argwhere(arr>1) #返回数组中所有大于1的数字的索引值。

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [240]:
h = 10
w = 3
mask_layer = np.zeros((h,w, 3), np.uint8)
# mask_layer
color = (0,0,0) # rgb

mask_layer == color

pixels = np.argwhere(mask_layer == color)
# pixels

In [247]:
arr = np.array([[0, 1, 2],
       [3, 4, 5]])
arr[::2,:] # star end step  #注意有逗号和没逗号的区分

array([[0, 1, 2]])