In [1]:
import numpy as np
#ndarray高效的多维数组，便捷的算术功能和灵活的广播功能

# ndarray

In [2]:
np.arange(100) #numpy版本的 range 的ndarray
#type(np.arange(100)) #numpy.ndarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
np.random.rand(2,3) #rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1

array([[0.89199571, 0.51772726, 0.64159027],
       [0.75270486, 0.32134083, 0.95337597]])

In [4]:
np.random.randn(2,3) #返回一个或一组样本，具有标准正态分布。

array([[-0.075917  , -0.34828164, -0.64694155],
       [ 0.29311645, -1.29848842,  0.26311527]])

## np.array

In [12]:
arr = np.array([1,2,3])
type(arr)  # numpy.ndarray
arr.shape # (3,)
arr.ndim # 1

1

In [18]:
arr2 = np.random.rand(3,5)
arr2.shape # (3, 5)
arr2.ndim # 2

2

In [21]:
arr3 = np.random.rand(3,5,2)
arr3.shape # (3, 5, 2)
arr3.ndim # 3

3

## np.empty

In [22]:
np.empty((2,3)) #并不安全，有时候会返回为初始化的垃圾数值
np.empty((2,3,2))

array([[[4.67679745e-310, 0.00000000e+000],
        [1.03977794e-312, 9.54898106e-313],
        [1.08221785e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.10343781e-312],
        [1.10343781e-312, 9.76118064e-313],
        [1.16709769e-312, 1.90979621e-312]]])

## np.zeros

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.ones

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## numpy.full

In [26]:
np.full((2,3),8,dtype='int64')

array([[8, 8, 8],
       [8, 8, 8]])

# 算术和广播

In [28]:
k = np.random.rand(2,3)
k

array([[0.12919611, 0.28649054, 0.45151874],
       [0.79475645, 0.06446997, 0.22706756]])

In [29]:
k+k

array([[0.25839222, 0.57298108, 0.90303748],
       [1.58951289, 0.12893994, 0.45413512]])

In [30]:
k*10

array([[1.29196108, 2.86490542, 4.51518739],
       [7.94756446, 0.64469971, 2.27067559]])

In [ ]:
k