# 矩阵库 numpy.matlib

In [1]:
import numpy.matlib 
import numpy as np 

In [2]:
np.matlib.empty((2,2))

matrix([[4.68705690e-310, 0.00000000e+000],
        [1.58101007e-322, 7.10236533e+194]])

In [3]:
np.matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [4]:
np.matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [5]:
np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [6]:
np.matlib.identity(5, dtype =  float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [7]:
d = np.array([[1,2],[3,4]])
np.asmatrix (d)  

matrix([[1, 2],
        [3, 4]])

# 线性代数 linalg

## 点积 np.dot

### 2x2矩阵

![图片](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171716937.png)

In [43]:
# 对 3,4向量进行向左旋转90度
np.dot([[0,-1],
        [1,0]],
       [3,4])

array([-4,  3])

In [46]:
# 对1，1向量 shear变换
np.dot([[1,1],
        [0,1]],
      [1,1])

array([2, 1])

In [48]:
# 什么也不做的变换
np.dot([[1, 0],
        [0, 1]],[2,8])

array([2, 8])

In [53]:
# 两个矩阵的乘，比如上面例子中的M1 M2. 注意还是按顺序些，但是计算其实是从右往左
np.dot(
       [[0, 2],
        [1, 0]]       
       ,
       [[1, -2],
        [1, 0]]
      )

array([[ 2,  0],
       [ 1, -2]])

### 3x3矩阵

![33](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171735620.png)

In [55]:
np.dot([
    [0, 1, 2],
    [3, 4, 5],
    [4, 7, 8]
],[1,2,3])

array([ 8, 26, 42])

### 向量对齐程度

![图](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171757238.png)

In [67]:
np.dot([2,7,1],[8,2,8])

38

In [68]:
np.dot([1,2],[3,4])

11

In [72]:
# 同向最大
np.dot([0,1],[0,2])

2

In [71]:
# 反向最大
np.dot([0,1],[0,-2])

-2

In [73]:
# 垂直
np.dot([1,0],[0,1])

0

In [93]:
# 这种情况下 调换顺序结果是一样的，但是用于矩阵的线性变化需要正确的顺序
np.dot([0,2],[0,1])
# 两个向量点积顺序无关.这是对偶性
# u · v = |u| · |v| · cos(θ)

2

## 行列式 det

![图](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171744117.png)

### 2x2矩阵

In [56]:
np.linalg.det([[3,0],
               [0,2]])
# i 基3,0 . j基 0,2

6.0

In [58]:
np.linalg.det([[0,2],
               [3,0]])

-6.0

In [60]:
np.linalg.det([[1,2],
               [1,2]])
# 两个点在一条线上

0.0

In [61]:
np.linalg.det([[3,2],
               [1,2]])

4.000000000000001

### 3x3矩阵

In [32]:
np.linalg.det([[6,   1,   1],
               [4,  -2,   5], 
               [2,   8,   7]])

-306.0

In [62]:
6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)

-306

In [63]:
np.linalg.det([[1,   0,   0],
               [0,   1,   0], 
               [0,   0,   1]])

1.0

In [64]:
np.linalg.det([[2,   0,   0],
               [0,   2,   0], 
               [0,   0,   2]])

7.999999999999998

## 叉乘（np.cross）

![图](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171812194.png)

In [84]:
np.cross([3,1],[2,-1])
### 返回的仍然是响量，大小是det. 坐标是在z轴上

array(-5)

In [86]:
### 顺序是重要的
np.cross([2,-1],[3,1])

array(5)

In [87]:
np.linalg.det([[3,2],
               [1,-1]])

-5.000000000000001

In [90]:
### 给三个坐标
np.cross([3,1,0],[2,-1, 0])

array([ 0,  0, -5])

In [92]:
np.cross([1,2,3],[4,5,6])

array([-3,  6, -3])

## 逆矩阵 linalg.inv()


![图](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171836434.png)

### 旋转的逆矩阵

In [111]:
x = [[0, -1],
     [1, 0]
]

In [101]:
y = np.linalg.inv(x)
y

array([[ 0.,  1.],
       [-1., -0.]])

In [102]:
np.dot(x,y)

array([[1., 0.],
       [0., 1.]])

### 剪切的逆

In [109]:
x2 = [[1, 1],
     [0, 1]
]

In [110]:
y2 = np.linalg.inv(x2)
y2

array([[ 1., -1.],
       [ 0.,  1.]])

In [107]:
np.dot(x2,y2)

array([[1., 0.],
       [0., 1.]])

## 非方阵

![非方阵](https://appen-pe.oss-cn-shanghai.aliyuncs.com/imgupload/202204171838187.png)

In [ ]:

import numpy as np
from scipy.spatial.transform import Rotation

### 欧拉角转四元数
p1 = [0,1,0] # y轴上的点1

q1 = Rotation.from_euler('xyz', [0, 0, -3.14], degrees=False).as_quat() # z方向旋转180读，右手坐标系下是往右旋转

m1 = Rotation.from_quat(q1).as_matrix()
# print(m1)
# [[-0.99999873  0.00159265  0.        ]
#  [-0.00159265 -0.99999873 -0.        ]
#  [-0.          0.          1.        ]]

'''
以上约等于，竖列

-1 0  0
0 -1 0 
0  0  1

1 0 0
0 1 0
0 0 1

'''


print(np.dot(m1,
       [1,0,0]))
print(np.dot(m1,
       [0,1,0]))
print(np.dot(m1,
       [0,0,1]))
