# 矩阵库 numpy.matlib

In [1]:
import numpy.matlib 
import numpy as np 

In [2]:
np.matlib.empty((2,2))

matrix([[4.68705690e-310, 0.00000000e+000],
        [1.58101007e-322, 7.10236533e+194]])

In [3]:
np.matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [4]:
np.matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [5]:
np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [6]:
np.matlib.identity(5, dtype =  float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [7]:
d = np.array([[1,2],[3,4]])
np.asmatrix (d)  

matrix([[1, 2],
        [3, 4]])

# 线性代数 linalg

## 点积（内积)

In [12]:
a = np.array([1,2])
b = np.array([3,4])
print(np.dot(a,b))

#1*3 +2*4

11


In [14]:
np.dot([0,1],[1,0])

0

In [15]:
np.dot([1,1],[1,0])

1

In [17]:
np.dot([1,0],[-1,1]) # 锐角负

-1

In [18]:
np.dot([1,1],[1,1])

2

In [21]:
# 几何意义
a = np.array([[1,2],
              [3,4]])

b = np.array([[11,12],
              [13,14]])
print(np.dot(a,b))


[[1*11+2*13, 1*12+2*14],
 [3*11+4*13, 3*12+4*14]]

[[37 40]
 [85 92]]


[[37, 40], [85, 92]]

In [22]:
np.inner([0,1],[1,0])

0

In [23]:
np.inner([1,1],[1,0])

1

In [24]:
np.inner([1,0],[-1,1])

-1

In [25]:
np.inner([1,1],[1,1])

2